"""
Font backend protocols.

Any backend must implement ReadableFontBackend.
Backends that support editing must also implement WritableFontBackend.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..classes import FontInfo, FontSource, GlobalAxis, VariableGlyph


@runtime_checkable
class ReadableFontBackend(Protocol):
    async def getGlyph(self, glyphName: str) -> VariableGlyph | None: ...
    async def getGlyphMap(self) -> dict[str, list[int]]: ...
    async def getAxes(self) -> list[GlobalAxis]: ...
    async def getSources(self) -> dict[str, FontSource]: ...
    async def getFontInfo(self) -> FontInfo: ...
    async def getUnitsPerEm(self) -> int: ...
    async def aclose(self) -> None: ...


@runtime_checkable
class WritableFontBackend(ReadableFontBackend, Protocol):
    async def putGlyph(
        self, glyphName: str, glyph: VariableGlyph, codePoints: list[int]
    ) -> None: ...
    async def putFontInfo(self, fontInfo: FontInfo) -> None: ...
    async def deleteGlyph(self, glyphName: str) -> None: ...
